### ISSUE TITLE
Unable to design primers

### ISSUE THREAD

**Issue by vinay7623** [MatthewHiggins2017/PrimedRPA#1]
Installed the program as instructed. Got a csv for validation run. However when i try and make changes to the primer parameter file and input file in the working directory no output is generated
![Screenshot from 2019-11-17 15-21-29](https://user-images.githubusercontent.com/57824242/69005891-36d13200-094e-11ea-9fa7-a9347edf19ab.png)
![Screenshot from 2019-11-17 15-21-50](https://user-images.githubusercontent.com/57824242/69005892-36d13200-094e-11ea-97e1-b8e084c5a564.png)
![Screenshot from 2019-11-17 15-21-57](https://user-images.githubusercontent.com/57824242/69005893-36d13200-094e-11ea-80c8-923bbbd888aa.png)
![Screenshot from 2019-11-17 15-22-03](https://user-images.githubusercontent.com/57824242/69005895-36d13200-094e-11ea-91ef-bb404ffe598a.png)
![Screenshot from 2019-11-17 15-22-11](https://user-images.githubusercontent.com/57824242/69005896-3769c880-094e-11ea-9e9c-b6ba2f617367.png)

**Comment by MatthewHiggins2017** [comment]
Hi @vinay7623, I believe this issue was caused by an error in the original PrimedRPA_Parameters.txt file which I corrected earlier today and pushed to this repository. Please download the updated PrimedRPA_Parameters.txt file and let me know if you encounter any more errors. 

Kind regards,
Matt.

**Comment by vinay7623** [comment]
Thanks, Matthew for the response!
